### ISSUE TITLE
Events issue when group has no tags

### ISSUE THREAD

**Issue by BSteephenson** [zfrenchee/Bluemoon#20]
I made a group with no tags. I made an event.
I put a console log right before returning fetched Events in EventsController
I get this
```
...stuff...
tags: null
...stuff...
```

It won't show up on the main page either due to a JS error.
Where should this be made into an empty array? Is Sails turning the empty array we give it into null? Is it on the front end?

**Comment by lyra833** [comment]
Ah, that makes sense. Event tags might be a good long term feature, then.

**Comment by zfrenchee** [comment]
We need to reach some sort of temporary conclusion and close this issue. I think the play is to have you, @BSteephenson make a small PR that causes the backend to insist that groups have at least one tag. Is that generally what we've agreed to?
