### ISSUE TITLE
Prettier Events Page designs

### ISSUE THREAD

**Issue by BSteephenson** [zfrenchee/Bluemoon#23]
![](https://d13yacurqjgara.cloudfront.net/users/95895/screenshots/995762/attachments/116901/calendar_dribbble_giant.jpg)
![](https://d13yacurqjgara.cloudfront.net/users/216526/screenshots/1992949/calendar_widget_1x.png)

Stolen from dribble duh
Would be amazing if Tufts Life looked like the second picture

**Comment by zfrenchee** [comment]
Link us? 

I don't think the second image will work, personally, but it's a thought. Thanks for posting this before the meeting on Thursday -- that gives us some food for thought. 

I recommend you checkout old tuftslife on the wayback machine, just to get an idea of where we come from.

**Comment by zfrenchee** [comment]
![screen shot 2015-03-31 at 3 22 11 pm](https://cloud.githubusercontent.com/assets/2761597/6927195/cd5b3a66-d7b9-11e4-8f79-184b4f582fbb.png)

**Comment by zfrenchee** [comment]
We should have the initial page filled with an agglomeration of widgets, I think, ideally a list of important links. and either a) Clicking the tuftslife logo should bring them back up or b) they should all be in a tab.

**Comment by lyra833** [comment]
Tab, 100% a tab, the last thing we need is for the interface to look too
busy.

**Comment by zfrenchee** [comment]
Interesting that you feel that way. I would personally go for links appearing on the empty initial screen.

**Comment by BSteephenson** [comment]
I'm all about that psuedo-minimalism. Big scary dashboards look soo 2003

![](https://d13yacurqjgara.cloudfront.net/users/10149/screenshots/1092955/screen_shot_2013-05-30_at_7.35.04_am.png)
![](https://d13yacurqjgara.cloudfront.net/users/125056/screenshots/1706861/top-menu_1-2-2.gif)
![](https://d13yacurqjgara.cloudfront.net/users/386467/screenshots/2000702/dots_1x.png)
![](https://d13yacurqjgara.cloudfront.net/users/324709/screenshots/1999409/weather_1x.png)
![](https://d13yacurqjgara.cloudfront.net/users/113062/screenshots/2000396/atv_events-calendar_1x.jpg)
![](https://d13yacurqjgara.cloudfront.net/users/15015/screenshots/1998791/activity_card_1x.png)
![](https://d13yacurqjgara.cloudfront.net/users/234651/screenshots/1989269/pleasure1.gif)

**Comment by BSteephenson** [comment]
This library is super sexy
http://materializecss.com/cards.html

**Comment by zfrenchee** [comment]
Note: we don't really want to focus on mobile views right now. 

Material is a google design language, which isn't quite flat I think. We want to keep to white and flat, ideally. Materializecss seems like a framework some kids worked on -- i'm not sure I want their css in our codebase. There are better frameworks around material + we already have bootstrap. Check [bootstrap components](http://getbootstrap.com/components/) to know what we already have to work with. 

We have a couple designers onboard, so we'll have them help us figure out the final look and feel. What we need to do thursday is really nail down what we want on the page, not exactly how it needs to look. We need to do some layout.

**Comment by zfrenchee** [comment]
![11137691_10153284324583060_1540785611_o](https://cloud.githubusercontent.com/assets/2761597/7008817/d8babca2-dc63-11e4-8bda-cf0621ac327b.jpg)
