### ISSUE TITLE
Back end: How to get a User's Groups' Events

### ISSUE THREAD

**Issue by BSteephenson** [zfrenchee/Bluemoon#26]
Do it in UserController::user ?
Do it in EventController::getEventsByGroup(groupName) ?

**Comment by lyra833** [comment]
I'd say do it in user, and have the call look like
```getEvents(getGroups())```. More extensibility, and we can just overload
```getEvents``` to take multiple groups.

**Comment by zfrenchee** [comment]
What exactly is the context of this question? I think we'll be able to reason about it better if you provide us with a little more context. When do you want a user's group's events? When they open the change event modal I assume? Personally it makes most sense to me to map over the user's groups and call GroupController::getGroup.populate(Events) or something.

**Comment by zfrenchee** [comment]
On second thought, I think that if we're looking to build something that is fired when the user hits 'change event' then that should probably be handled by the eventController, right?

**Comment by BSteephenson** [comment]
Before the user clicks "change event", should UserModel know all the events owned by all the groups? Or should that be found out (via an API call) after the user picks a group?

**Comment by zfrenchee** [comment]
Neither, I think. Once the user clicks 'change event' then we make an API call to get all the events from all the groups. Or we can go with your second idea. I think the first idea is way too much work.

**Comment by BSteephenson** [comment]
Doing it in User -> least amount of code on both front end and backend. Simplest to work with. Worst performance.

Doing it when user clicks 'change event' -> more front end code, callbacks, populating the lists might happen after the modal is shown to the user. Better performance (only getting those events when you need them)

**Comment by zfrenchee** [comment]
I think there are a lot more parameters than that. Where you put the code and when you call it are orthogonal, so we actually have more like 6 choices, each of which with a different amount of code and performance profile. We shall discuss this further.
