### ISSUE TITLE
Groups Tab

### ISSUE THREAD

**Issue by zfrenchee** [zfrenchee/Bluemoon#28]
I Think that a lot of freshman coming onto the tufts campus for the first time would benefit from a good directory of the groups on campus and a way to contact them. We should already have all the groups together in a db, we should put them all together in a tab. 

This could be a really beautiful page if we had images *everywhere*.

**Comment by BSteephenson** [comment]
It would be snazzy if we could let groups use markdown for their descriptions. That way we wouldn't even really need to manage pictures at all. Just get them to use imgur or something.

Power to the users!

**Comment by zfrenchee** [comment]
I'm going to add it to the 'To Do' list on trello.
