### ISSUE TITLE
Our page load time is slowing down a lot lately.

### ISSUE THREAD

**Issue by zfrenchee** [zfrenchee/Bluemoon#30]
That might just be the fact I have too many tabs open on this laptop, but I think we need to keep watch over this issue. Worse, some things load before others, like a piece of text loads, then the JS loads which tells it to keep hidden. It might be nice to work on that at some point.

**Comment by BSteephenson** [comment]
According to Safari, sails.io.js takes
- 703ms of layout rendering
> 1.2 seconds firing random events

Can we get rid of it until we need it. It's just sockets right? Rename it to something like sails.io.js.ignore

**Comment by BSteephenson** [comment]
...and it goes from 2.5 seconds to 1.5 seconds woohooo. Still shows html without css before hand for a fraction of a second

**Comment by zfrenchee** [comment]
What is sails.io.js?

**Comment by BSteephenson** [comment]
The thingy that integrates Sails with socket.io

**Comment by zfrenchee** [comment]
Okay. Turn it off, and open a PR for that. I don't want to get rid of it entirely, because socket.io is apparently 'The Way' ®.
