### ISSUE TITLE
Forgot you password and Change your password

### ISSUE THREAD

**Issue by BSteephenson** [zfrenchee/Bluemoon#35]
I see three options

## A
"Forgot your password" changes you password to gibberish and emails it to you
You then log in and change your password to whatever

Cons
- people being assholes and resetting others' passwords

## B
"Forgot your password" sends you a link which take you to a form that let's you change your password
(I feel like most sites do this)

Cons
- having to make another form (oh the horror) and using some sort of crypto magic to associate a URL with a user and stuff

=========

I like Option A. Seems easier. The con doesn't seem too likely. What's the best? What other ideas yalls have?

**Comment by zfrenchee** [comment]
Isn't A basically a superset of B? Part 2 of A ('change password') is itself a form. 
I actually have learned some crypto magic over the course of this project, so don't worry too much on that front. I think B works, but we might be able to find something better. What about a security question? 1 option: "What was the name of that [ girl | guy ] you were totally into when you arrived at Tufts but you never mentioned it to them and you're still into them now but you aren't sure they know you exist?" *Everyone* has an answer to that question

**Comment by zfrenchee** [comment]
Going to close this for now. We'll re-open this once  we actually need this feature implemented. For now, I think we can rely on people remembering their passwords in the short term.
